[package]
name = "phoenix-macros"
description = "Contract marker macros for Phoenix code generation"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "full", "parsing", "printing"] }

[lints]
workspace = true
